name: Publish Python Package (PyPi)

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: pip install --no-input poetry

      - name: Bump Poetry version
        run: |
          tag=${{ github.event.release.tag_name }}
          version_number=${tag#?}
          poetry version $version_number

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Bump version to ${{ github.event.release.tag_name }}"
          add: "pyproject.toml"
          ref: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish to PyPi
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish --build
